# Declarative list of tools for workstation setup using a flat tools-list schema.
#
# Fields:
#   name       - unique identifier for the tool (quoted if it contains special chars)
#   category   - high-level grouping (e.g., languages, editors, terminals, cli_tools, apps, gui_apps, dotfiles)
#   phase      - install phase (prerequisites, packages, casks, apps, postinstall)
#   installer  - installation type for Homebrew (formula or cask) or other manager
#   os         - list of OS targets (macos, linux, windows)
#   enabled    - true to auto-install, false to skip
#   manual     - true to log for manual install instead of automated
#   version    - optional version constraint or explicit version string
#   depends_on - optional list of tool names that must install first
#
# Example entry for iTerm2 on macOS:
tools:
  - name: "iterm2"
    category: "terminals"
    phase: "apps"
    installer: "cask"
    os:
      - macos
    enabled: true
    manual: false
    version: ""      # leave empty or remove if not needed
    depends_on: []   # add tool names here if this has dependencies